### ISSUE TITLE
provide a go client for the Go ChargePoint implementation

### ISSUE THREAD

**Issue by mkbhanda** [CamusEnergy/kinney#15]
The Go implementation of the Chargepoint SOAP calls is awesome. We anticipate clients making the calls programmatically.

The client could be initiated with environment variables such as api-key, password and charge point web service url.

We could have methods such as getLoad, curtail, and clear that take in arguments such as station-group, station-id, port-id, and for curtail the amount too (either percentage or absolute amount to be specified).

**Comment by difince** [comment]
Once PR https://github.com/CamusEnergy/kinney/pull/14 is meger this functionality will be available

**Comment by mkbhanda** [comment]
Thanks Diana for the update and sharing that you used successfully.
