### ISSUE TITLE
Miss to check if err != nil

### ISSUE THREAD

**Issue by difince** [CamusEnergy/kinney#32]
Miss check if err != nil 
https://github.com/CamusEnergy/kinney/blob/b5347b93e991b926c40c545a4bf3d3a9b1033705/controller/chargepoint/simulator/sim/handlers.go#L45

**Comment by tzstoyanov** [comment]
`err` is check few lines below,  where `ResponseCode` and `ResponseText` are set according to it:
```
	if err == nil {
		resp.ResponseCode = "100"
		resp.ResponseText = "OK"
	} else {
		resp.ResponseCode = "102"
		resp.ResponseText = "No load recorded"
	}

```

**Comment by difince** [comment]
But it is too late if `s.Ev.getNextLoad(resp, group, &req.StationID) ` returns you an error  
(return fmt.Errorf("Station not found"))

**Comment by difince** [comment]
Yes, but it is a bil late
If we do getLoad by group id that does not exists -> group will stay with value `nil` and on the next line nil pointer exception will be raised.
https://github.com/CamusEnergy/kinney/blob/b5347b93e991b926c40c545a4bf3d3a9b1033705/controller/chargepoint/simulator/sim/handlers.go#L45-L48

If we check for error immediately - the exception will be skipped
